#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "client_search"
require "client_search/api_server"

begin
  require "dotenv"
  Dotenv.load
rescue LoadError
  # dotenv is not available
end

port = ENV["PORT"] || 3000

puts "Starting client search API server on http://localhost:#{port}"
puts "Use Ctrl+C to stop the server"

ClientSearch::ApiServer.run!(host: "localhost", port: port)
