name: Client Search CLI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.4-alpine
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Ruby environment
      uses: ./.github/actions/setup-ruby-alpine
      with:
        bundler-version: '2.4.22'
    
    - name: Run tests
      run: bundle exec rake spec
  
  lint:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.4-alpine
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Ruby environment
      uses: ./.github/actions/setup-ruby-alpine
      with:
        bundler-version: '2.4.22'
    
    - name: Run linter
      run: bundle exec rake rubocop 